// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Db } from "./Db";
import type { Namespace } from "./Namespace";

export interface JwtStruct { NS: Namespace, DB: Db, email: string, }